package Dichiarativo.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_TipoCampo extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TipoCampo() {
    super(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade990f95L, "TipoCampo", "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218453");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_N1_0 = new EnumerationDescriptor.MemberDescriptor("N1", "N1", 0x7d4e9bbade990f96L, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218454");
  private final EnumerationDescriptor.MemberDescriptor myMember_N2_0 = new EnumerationDescriptor.MemberDescriptor("N2", "N2", 0x7d4e9bbade990f97L, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218455");
  private final EnumerationDescriptor.MemberDescriptor myMember_N3_0 = new EnumerationDescriptor.MemberDescriptor("N3", "N3", 0x7d4e9bbade990f9aL, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218458");
  private final EnumerationDescriptor.MemberDescriptor myMember_N4_0 = new EnumerationDescriptor.MemberDescriptor("N4", "N4", 0x7d4e9bbade990f9eL, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218462");
  private final EnumerationDescriptor.MemberDescriptor myMember_NP_0 = new EnumerationDescriptor.MemberDescriptor("NP", "NP", 0x7d4e9bbade990fa3L, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218467");
  private final EnumerationDescriptor.MemberDescriptor myMember_CF_0 = new EnumerationDescriptor.MemberDescriptor("CF", "CF", 0x7d4e9bbade990fa9L, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218473");
  private final EnumerationDescriptor.MemberDescriptor myMember_CN_0 = new EnumerationDescriptor.MemberDescriptor("CN", "CN", 0x7d4e9bbade990fb0L, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218480");
  private final EnumerationDescriptor.MemberDescriptor myMember_PI_0 = new EnumerationDescriptor.MemberDescriptor("PI", "PI", 0x7d4e9bbade990fb8L, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218488");
  private final EnumerationDescriptor.MemberDescriptor myMember_DT_0 = new EnumerationDescriptor.MemberDescriptor("DT", "DT", 0x7d4e9bbade990fc1L, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218497");
  private final EnumerationDescriptor.MemberDescriptor myMember_NU_0 = new EnumerationDescriptor.MemberDescriptor("NU", "NU", 0x7d4e9bbade990fcbL, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218507");
  private final EnumerationDescriptor.MemberDescriptor myMember_PR_0 = new EnumerationDescriptor.MemberDescriptor("PR", "PR", 0x7d4e9bbade990fd6L, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218518");
  private final EnumerationDescriptor.MemberDescriptor myMember_CB_0 = new EnumerationDescriptor.MemberDescriptor("CB", "CB", 0x7d4e9bbade990fe2L, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218530");
  private final EnumerationDescriptor.MemberDescriptor myMember_VP_0 = new EnumerationDescriptor.MemberDescriptor("VP", "VP", 0x7d4e9bbade990fefL, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218543");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade990f95L, 0x7d4e9bbade990f96L, 0x7d4e9bbade990f97L, 0x7d4e9bbade990f9aL, 0x7d4e9bbade990f9eL, 0x7d4e9bbade990fa3L, 0x7d4e9bbade990fa9L, 0x7d4e9bbade990fb0L, 0x7d4e9bbade990fb8L, 0x7d4e9bbade990fc1L, 0x7d4e9bbade990fcbL, 0x7d4e9bbade990fd6L, 0x7d4e9bbade990fe2L, 0x7d4e9bbade990fefL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_N1_0, myMember_N2_0, myMember_N3_0, myMember_N4_0, myMember_NP_0, myMember_CF_0, myMember_CN_0, myMember_PI_0, myMember_DT_0, myMember_NU_0, myMember_PR_0, myMember_CB_0, myMember_VP_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "N1":
        return myMember_N1_0;
      case "N2":
        return myMember_N2_0;
      case "N3":
        return myMember_N3_0;
      case "N4":
        return myMember_N4_0;
      case "NP":
        return myMember_NP_0;
      case "CF":
        return myMember_CF_0;
      case "CN":
        return myMember_CN_0;
      case "PI":
        return myMember_PI_0;
      case "DT":
        return myMember_DT_0;
      case "NU":
        return myMember_NU_0;
      case "PR":
        return myMember_PR_0;
      case "CB":
        return myMember_CB_0;
      case "VP":
        return myMember_VP_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
