package Dichiarativo.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_OrigineValore extends EnumerationDescriptorBase {

  public EnumerationDescriptor_OrigineValore() {
    super(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade991008L, "OrigineValore", "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218568");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Calcolato_0 = new EnumerationDescriptor.MemberDescriptor("Calcolato", "Calcolato", 0x7d4e9bbade991009L, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218569");
  private final EnumerationDescriptor.MemberDescriptor myMember_Contabilita_0 = new EnumerationDescriptor.MemberDescriptor("Contabilita", "Contabilita", 0x7d4e9bbade99100aL, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218570");
  private final EnumerationDescriptor.MemberDescriptor myMember_Manuale_0 = new EnumerationDescriptor.MemberDescriptor("Manuale", "Manuale", 0x7d4e9bbade99100dL, "r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218573");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade991008L, 0x7d4e9bbade991009L, 0x7d4e9bbade99100aL, 0x7d4e9bbade99100dL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Calcolato_0, myMember_Contabilita_0, myMember_Manuale_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Calcolato":
        return myMember_Calcolato_0;
      case "Contabilita":
        return myMember_Contabilita_0;
      case "Manuale":
        return myMember_Manuale_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
