package Dichiarativo.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Campo = 0;
  public static final int CampoNonPosizionale = 1;
  public static final int CampoPosizionale = 2;
  public static final int Dichiarazione = 3;
  public static final int Quadro = 4;
  public static final int QuadroReference = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L);
    builder.put(0x7d4e9bbade991005L, Campo);
    builder.put(0x7d4e9bbade99101dL, CampoNonPosizionale);
    builder.put(0x7d4e9bbade991020L, CampoPosizionale);
    builder.put(0x7d4e9bbade990f92L, Dichiarazione);
    builder.put(0x7d4e9bbade990ffdL, Quadro);
    builder.put(0x7d4e9bbade991000L, QuadroReference);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
