package Dichiarativo.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCampo = createDescriptorForCampo();
  /*package*/ final ConceptDescriptor myConceptCampoNonPosizionale = createDescriptorForCampoNonPosizionale();
  /*package*/ final ConceptDescriptor myConceptCampoPosizionale = createDescriptorForCampoPosizionale();
  /*package*/ final ConceptDescriptor myConceptDichiarazione = createDescriptorForDichiarazione();
  /*package*/ final ConceptDescriptor myConceptQuadro = createDescriptorForQuadro();
  /*package*/ final ConceptDescriptor myConceptQuadroReference = createDescriptorForQuadroReference();
  /*package*/ final EnumerationDescriptor myEnumerationOrigineValore = new EnumerationDescriptor_OrigineValore();
  /*package*/ final EnumerationDescriptor myEnumerationTipoCampo = new EnumerationDescriptor_TipoCampo();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCampo, myConceptCampoNonPosizionale, myConceptCampoPosizionale, myConceptDichiarazione, myConceptQuadro, myConceptQuadroReference);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Campo:
        return myConceptCampo;
      case LanguageConceptSwitch.CampoNonPosizionale:
        return myConceptCampoNonPosizionale;
      case LanguageConceptSwitch.CampoPosizionale:
        return myConceptCampoPosizionale;
      case LanguageConceptSwitch.Dichiarazione:
        return myConceptDichiarazione;
      case LanguageConceptSwitch.Quadro:
        return myConceptQuadro;
      case LanguageConceptSwitch.QuadroReference:
        return myConceptQuadroReference;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationOrigineValore, myEnumerationTipoCampo);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCampo() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Dichiarativo", "Campo", 0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade991005L);
    b.class_(false, true, false);
    b.origin("r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218565");
    b.version(3);
    b.property("Tipo", 0x7d4e9bbade991006L).type(MetaIdFactory.dataTypeId(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade990f95L)).origin("9029325529825218566").done();
    b.property("Origine", 0x7d4e9bbade991011L).type(MetaIdFactory.dataTypeId(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade991008L)).origin("9029325529825218577").done();
    b.alias("Campo");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCampoNonPosizionale() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Dichiarativo", "CampoNonPosizionale", 0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade99101dL);
    b.class_(false, false, false);
    // extends: Dichiarativo.structure.Campo
    b.super_(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade991005L);
    b.origin("r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218589");
    b.version(3);
    b.property("codice", 0x7d4e9bbade99101eL).type(PrimitiveTypeId.STRING).origin("9029325529825218590").done();
    b.alias("CampoN");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCampoPosizionale() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Dichiarativo", "CampoPosizionale", 0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade991020L);
    b.class_(false, false, false);
    // extends: Dichiarativo.structure.Campo
    b.super_(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade991005L);
    b.origin("r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218592");
    b.version(3);
    b.property("nome", 0x7d4e9bbade991021L).type(PrimitiveTypeId.STRING).origin("9029325529825218593").done();
    b.property("posizione", 0x7d4e9bbade991023L).type(PrimitiveTypeId.INTEGER).origin("9029325529825218595").done();
    b.property("lunghezza", 0x7d4e9bbade991026L).type(PrimitiveTypeId.INTEGER).origin("9029325529825218598").done();
    b.alias("campoP");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDichiarazione() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Dichiarativo", "Dichiarazione", 0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade990f92L);
    b.class_(false, false, true);
    b.origin("r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218450");
    b.version(3);
    b.property("Nome", 0x7d4e9bbade990f93L).type(PrimitiveTypeId.STRING).origin("9029325529825218451").done();
    b.aggregate("quadri", 0x7d4e9bbade991003L).target(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade991000L).optional(true).ordered(true).multiple(false).origin("9029325529825218563").done();
    b.alias("Dichiarazione");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQuadro() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Dichiarativo", "Quadro", 0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade990ffdL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218557");
    b.version(3);
    b.property("Nome", 0x7d4e9bbade991016L).type(PrimitiveTypeId.STRING).origin("9029325529825218582").done();
    b.property("MultiModulo", 0x7d4e9bbade991018L).type(PrimitiveTypeId.BOOLEAN).origin("9029325529825218584").done();
    b.aggregate("Campi", 0x7d4e9bbade99101bL).target(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade991005L).optional(false).ordered(true).multiple(true).origin("9029325529825218587").done();
    b.alias("Quadro");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQuadroReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Dichiarativo", "QuadroReference", 0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade991000L);
    b.class_(false, false, false);
    b.origin("r:e7e9085c-465f-4042-979b-f2aa047e494b(Dichiarativo.structure)/9029325529825218560");
    b.version(3);
    b.associate("Refers", 0x7d4e9bbade991001L).target(0x1a9fc8c7feb0472dL, 0xa0db0b63897ca4c6L, 0x7d4e9bbade990ffdL).optional(false).origin("9029325529825218561").done();
    b.alias("quadro");
    return b.create();
  }
}
